version: "3.7"

networks:
  dtsp_bridge:

services:

  dtsp-db-mysql:
    build:
      context: ./dtsp-db-mysql
    image: dtsp/dtsp-db-mysql:latest
    ports:
      - 3307:3306
    networks:
      - dtsp_bridge

  dtsp-zabbix-server:
    image: dtsp/dtsp-zabbix-server
    networks:
      - dtsp_bridge
    environment:
     - DB_SERVER_HOST=dtsp-db-mysql
     - DB_SERVER_PORT=3307
     - MYSQL_USER=zabbix
     - MYSQL_PASSWORD=zabbix
     - MYSQL_DATABASE=zabbix