version: "3.7"

networks:
  zab_bridge:

services:
  zabbix-db-mysql:
    build:
      context: ./zabbix-db-mysql
    image: dtsp/zabbix-db-mysql:latest
    ports:
      - 3307:3306
    networks:
      - zab_bridge