version: "3.7"

networks:
  dtsp_bridge:

services:

  dtsp-db-mysql:
    build:
      context: ./dtsp-db-mysql
    image: dtsp/dtsp-db-mysql:latest
    ports:
      - 3307:3306
    networks:
      - dtsp_bridge

  dtsp-zabbix-server:
    image: zabbix/zabbix-server-mysql
    networks:
      - dtsp_bridge
    environment:
     - DB_SERVER_HOST=dtsp-db-mysql
     - DB_SERVER_PORT=3306
     - MYSQL_USER=zabbix
     - MYSQL_PASSWORD=zabbix
     - MYSQL_DATABASE=zabbix
    depends_on:
      - dtsp-db-mysql

  dtsp-zabbix-web:
    image: zabbix/zabbix-web-apache-mysql:latest
    networks:
      - dtsp_bridge
    ports:
      - 9080:80
      - 9443:443
    environment:
     - ZBX_SERVER_HOST=dtsp-zabbix-server
     - ZBX_SERVER_PORT=10051
     - DB_SERVER_HOST=dtsp-db-mysql
     - DB_SERVER_PORT=3306
     - MYSQL_USER=zabbix
     - MYSQL_PASSWORD=zabbix
     - MYSQL_DATABASE=zabbix
     - PHP_TZ=Europe/Sofia
     - ZBX_SERVER_NAME=DTSP
    depends_on:
      - dtsp-zabbix-server